name = "SoEwald2D"
uuid = "0daaa638-a47d-40d8-b855-b9e525a61752"
authors = ["Xuanzhao Gao"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
